import { WriteupMetaData } from "./types";

export const TempMetaData: (WriteupMetaData | undefined)[] = [
  {
    Platform: "HackTheBox",
    Category: "Android",
    Difficulty: "Easy",
    Status: "Rooted/Finished",
    Type: "Challenge",
    Title: "APKey",
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Category: "Android",
    Difficulty: "Easy",
    Status: "Rooted/Finished",
    Type: "Challenge",
    Title: "APKrypt",
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Title: "Anchored",
    Platform: "HackTheBox",
    Type: "Challenge",
    Difficulty: "Easy",
    Category: "Android",
    Status: "Done",
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Difficulty: "Easy",
    tags: ["MS17-010", "RCE", "Windows"],
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "Blue",
    Category: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "TryHackMe",
    Difficulty: "Medium",
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "Capstone Challenge",
    Category: undefined,
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Category: "Android",
    Difficulty: "Easy",
    Status: "Rooted/Finished",
    Type: "Challenge",
    Title: "Cat",
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Difficulty: "Easy",
    tags: ["command-injection", "sudo-privesc"],
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "CozyHosting",
    Category: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Difficulty: "Easy",
    tags: ["Joomla", "apport-cli", "vhost"],
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "Devvortex",
    Category: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Category: "Android",
    Difficulty: "Very Easy",
    Status: "Rooted/Finished",
    Type: "Challenge",
    Title: "Don’t Overreact",
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "TryHackMe",
    Difficulty: "Medium",
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "Eavesdropper",
    Category: undefined,
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Category: "Android",
    Difficulty: "Easy",
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "Explore",
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Category: "Reversing",
    Difficulty: "Easy",
    Status: "Rooted/Finished",
    Type: "Challenge",
    Title: "Find The Easy Pass",
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Category: "Web",
    Difficulty: "Easy",
    tags: ["RCE", "arbitrary-file-upload", "default-credentials"],
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "Jerry",
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Difficulty: "Easy",
    tags: ["default-credentials"],
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "Keeper",
    Category: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Difficulty: "Easy",
    tags: ["RCE"],
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "Lame",
    Category: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Category: "Android",
    Difficulty: "Easy",
    Status: "Rooted/Finished",
    Type: "Challenge",
    Title: "Manager",
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "TryHackMe",
    Difficulty: "Medium",
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "Metamorphosis",
    Category: undefined,
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Difficulty: "Easy",
    tags: ["RCE", "anonymous-ftp"],
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "Netmon",
    Category: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "CreatedByMe",
    Category: "Web",
    tags: ["No-SQL-Injection", "suid"],
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "NoSQLInjection",
    Difficulty: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Category: "Web",
    Difficulty: "Easy",
    tags: ["No-SQL-Injection", "mongo-db", "nodejs"],
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "NodeBlog",
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "TryHackMe",
    Difficulty: "Easy",
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "Overpass 2 - Hacked",
    Category: undefined,
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "TryHackMe",
    Difficulty: "Medium",
    Status: "TODO",
    Type: "Machine",
    Title: "Overpass 3 - Hosting",
    Category: undefined,
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "TryHackMe",
    Difficulty: "Easy",
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "Overpass",
    Category: undefined,
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Difficulty: "Easy",
    tags: ["gRPC"],
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "PC",
    Category: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Difficulty: "Easy",
    tags: ["LFI", "RCE"],
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "Pilgrimage",
    Category: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Category: "Android",
    Difficulty: "Easy",
    tags: ["Android", "certificate-pinning-bypass", "frida"],
    Status: "Rooted/Finished",
    Type: "Challenge",
    Title: "Pinned",
    CreatedOn: "04-12-2023",
  },
  undefined,
  {
    Platform: "HackTheBox",
    Difficulty: "Easy",
    tags: ["RCE", "SSRF", "suid"],
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "Sau",
    Category: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Category: "Android",
    Difficulty: "Medium",
    Status: "TODO",
    Type: "Machine",
    Title: "SeeTheSharpFlag",
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "TryHackMe",
    Difficulty: "Easy",
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "Simple CTF",
    Category: undefined,
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Difficulty: "Easy",
    tags: ["ArbitraryFileUpload"],
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "Squashed",
    Category: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "TryHackMe",
    Difficulty: "Easy",
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "TakeOver",
    Category: undefined,
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Category: "Web",
    Difficulty: "Easy",
    tags: ["jinja", "template-injection"],
    Status: "Rooted/Finished",
    Type: "Challenge",
    Title: "Templated",
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Category: "Web",
    Difficulty: "Medium",
    Status: "Rooted/Finished",
    Type: "Challenge",
    Title: "Under Construction",
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Category: "Crypto",
    Difficulty: "Easy",
    Status: "Rooted/Finished",
    Type: "Challenge",
    Title: "Weak RSA",
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "HackTheBox",
    Category: "Pwn",
    Difficulty: "Easy",
    Status: "Rooted/Finished",
    Type: "Challenge",
    Title: "You know 0xDiablos",
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
  {
    Platform: "TryHackMe",
    Difficulty: "Easy",
    Status: "Rooted/Finished",
    Type: "Machine",
    Title: "b3dr0ck",
    Category: undefined,
    tags: undefined,
    CreatedOn: "04-12-2023",
  },
];
